# Generated by Django 5.2.5 on 2025-10-31 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('value', models.FloatField(default=0)),
                ('visto_por_ultimo', models.DateField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('on', models.BooleanField(default=False)),
                ('category_id', models.IntegerField()),
                ('category', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
